spring:
  application:
    name: agenda-service
  profiles:
    active: hml
  webflux:
    base-path: /agenda-service
  data:
    mongodb:
      uri: mongodb+srv://andersonpetro:ap1234@agenda-service.37uxstq.mongodb.net/agenda-service?retryWrites=true&w=majority
      auto-index-creation: false
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: http://localhost:8080/realms/agenda-service
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration

server:
  port: 9000

restclient:
  keycloak:
    baseurl: http://localhost:8080
    realm: agenda-service
    authorization-basic: Basic YXBwX2FnZW5kYTpyRERJRDM5SXVGVk1iZEhoanZtcjhCMGx3cWxONVdWZg==
  agenda-service:
    baseurl: http://localhost:9000
    token:
      header: app-token
      value: default-token

zoneid: America/Sao_Paulo

springdoc:
  swagger-ui:
    path: /swagger-ui.html

