spring:
  application:
    name: agenda-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/agenda-db
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/agenda-realm/protocol/openid-connect/certs

server:
  port: 9000

restclient:
  keycloak:
    baseurl: http://localhost:8080
    realm: agenda-realm
    authorization-basic: Basic Y2xpZW50LWlkOmNsaWVudC1zZWNyZXQ=
  agenda:
    baseurl: http://localhost:9000
    token:
      header: X-API-KEY
      value: default-token

zoneid: America/Sao_Paulo

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
