spring.application.name=agenda-service

spring.data.mongodb.uri=mongodb://localhost:27017/agenda-db
spring.data.mongodb.auto-index-creation=true

server.port=9000

restclient.keycloak.baseurl=http://localhost:8080
restclient.keycloak.realm=agenda-service-realm
restclient.keycloak.authorization-basic=Basic Y2xpZW50LWlkOmNsaWVudC1zZWNyZXQ=

restclient.agenda.baseurl=http://localhost:9000
restclient.agenda.token.header=X-API-KEY
restclient.agenda.token.value=default-token

zoneid=America/Sao_Paulo

springdoc.swagger-ui.path=/swagger-ui.html
